name: Publish NuGet package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Build nuget package
      run: dotnet pack src/Adia.TaskRateLimiter.csproj --configuration Release

    - name: Publish nuget package
      env:
        nugetApiKey: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push src/bin/Release/*.nupkg --source https://www.nuget.org --api-key $env:nugetApiKey
      shell: pwsh
